import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { trackStreamUrl, type TrackSummary } from '../api/music';

type RepeatMode = 'off' | 'track' | 'queue';
interface PlayerState { current: { track: TrackSummary } | null; playing: boolean; position: number; duration: number; queue: TrackSummary[]; queueIndex: number; repeatMode: RepeatMode; shuffle: boolean; toggle: (track: TrackSummary) => void; playQueue: (tracks: TrackSummary[], index?: number) => void; enqueue: (track: TrackSummary) => void; playNext: (track: TrackSummary) => void; next: () => void; previous: () => void; seek: (seconds: number) => void; setShuffle: (enabled: boolean) => void; cycleRepeat: () => void; stop: () => void; clearQueue: () => void; removeFromQueue: (trackId: string) => void; }
const PlayerContext = createContext<PlayerState | null>(null);
const STORAGE_KEY = 'onidash.player.v1';
type PersistedPlayer = { queue: TrackSummary[]; queueIndex: number; position: number; repeatMode: RepeatMode; shuffle: boolean };
function readPersisted(): PersistedPlayer { try { const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? 'null') as Partial<PersistedPlayer> | null; if (parsed && Array.isArray(parsed.queue)) return { queue: parsed.queue, queueIndex: Math.max(0, Math.min(parsed.queueIndex ?? 0, Math.max(0, parsed.queue.length - 1))), position: Math.max(0, parsed.position ?? 0), repeatMode: parsed.repeatMode === 'track' || parsed.repeatMode === 'queue' ? parsed.repeatMode : 'off', shuffle: parsed.shuffle === true }; } catch {} return { queue: [], queueIndex: 0, position: 0, repeatMode: 'off', shuffle: false }; }

export function PlayerProvider({ children }: { children: ReactNode }) {
  const audioRef = useRef<HTMLAudioElement | null>(null); const initial = useMemo(readPersisted, []); const [queue, setQueue] = useState(initial.queue); const [queueIndex, setQueueIndex] = useState(initial.queueIndex); const [current, setCurrent] = useState<TrackSummary | null>(initial.queue[initial.queueIndex] ?? null); const [playing, setPlaying] = useState(false); const [position, setPosition] = useState(initial.position); const [duration, setDuration] = useState(initial.queue[initial.queueIndex]?.durationSeconds ?? 0); const [repeatMode, setRepeatMode] = useState<RepeatMode>(initial.repeatMode); const [shuffle, setShuffleState] = useState(initial.shuffle); const saveTimer = useRef<number | undefined>(undefined);
  const persist = useCallback((next: Partial<PersistedPlayer> = {}) => { window.clearTimeout(saveTimer.current); saveTimer.current = window.setTimeout(() => localStorage.setItem(STORAGE_KEY, JSON.stringify({ queue: next.queue ?? queue, queueIndex: next.queueIndex ?? queueIndex, position: next.position ?? position, repeatMode: next.repeatMode ?? repeatMode, shuffle: next.shuffle ?? shuffle })), 250); }, [position, queue, queueIndex, repeatMode, shuffle]);
  const loadTrack = useCallback((track: TrackSummary, index: number, autoplay = true, startPosition = 0) => { const audio = audioRef.current; setCurrent(track); setQueueIndex(index); setPosition(startPosition); setDuration(track.durationSeconds ?? 0); if (!audio) return; audio.src = trackStreamUrl(track.id); audio.currentTime = startPosition; if (autoplay) { setPlaying(true); void audio.play().catch(() => setPlaying(false)); } }, []);
  const playQueue = useCallback((tracks: TrackSummary[], index = 0) => { if (!tracks.length) return; const safe = Math.max(0, Math.min(index, tracks.length - 1)); setQueue(tracks); loadTrack(tracks[safe], safe); persist({ queue: tracks, queueIndex: safe, position: 0 }); }, [loadTrack, persist]);
  const toggle = useCallback((track: TrackSummary) => { const audio = audioRef.current; if (!audio) return; if (current?.id === track.id) { if (audio.paused) { setPlaying(true); void audio.play().catch(() => setPlaying(false)); } else audio.pause(); return; } const existing = queue.findIndex((item) => item.id === track.id); existing >= 0 ? loadTrack(track, existing) : playQueue([track]); }, [current?.id, loadTrack, playQueue, queue]);
  const enqueue = useCallback((track: TrackSummary) => { setQueue((items) => { if (items.some((item) => item.id === track.id)) return items; const next = [...items, track]; persist({ queue: next }); return next; }); }, [persist]);
  const playNext = useCallback((track: TrackSummary) => { setQueue((items) => { const without = items.filter((item) => item.id !== track.id); const insertAt = Math.min(queueIndex + 1, without.length); const next = [...without.slice(0, insertAt), track, ...without.slice(insertAt)]; persist({ queue: next }); return next; }); }, [persist, queueIndex]);
  const next = useCallback(() => { if (!queue.length) return; if (repeatMode === 'track' && current) { loadTrack(current, queueIndex); return; } let nextIndex = shuffle && queue.length > 1 ? Math.floor(Math.random() * queue.length) : queueIndex + 1; if (nextIndex >= queue.length) { if (repeatMode !== 'queue') { setPlaying(false); return; } nextIndex = 0; } loadTrack(queue[nextIndex], nextIndex); persist({ queueIndex: nextIndex, position: 0 }); }, [current, loadTrack, persist, queue, queueIndex, repeatMode, shuffle]);
  const previous = useCallback(() => { if (audioRef.current && audioRef.current.currentTime > 5) { audioRef.current.currentTime = 0; setPosition(0); return; } const index = Math.max(0, queueIndex - 1); if (queue[index]) loadTrack(queue[index], index); }, [loadTrack, queue, queueIndex]);
  const seek = useCallback((seconds: number) => { const audio = audioRef.current; if (audio && Number.isFinite(seconds)) { audio.currentTime = seconds; setPosition(seconds); } }, []);
  const setShuffle = useCallback((enabled: boolean) => { setShuffleState(enabled); persist({ shuffle: enabled }); }, [persist]);
  const cycleRepeat = useCallback(() => { setRepeatMode((mode) => { const nextMode = mode === 'off' ? 'track' : mode === 'track' ? 'queue' : 'off'; persist({ repeatMode: nextMode }); return nextMode; }); }, [persist]);
  const clearQueue = useCallback(() => { const keep = current ? [current] : []; setQueue(keep); setQueueIndex(0); persist({ queue: keep, queueIndex: 0 }); }, [current, persist]);
  const removeFromQueue = useCallback((trackId: string) => { setQueue((items) => { const index = items.findIndex((item) => item.id === trackId); if (index < 0) return items; const next = items.filter((item) => item.id !== trackId); const nextIndex = index < queueIndex ? queueIndex - 1 : Math.min(queueIndex, Math.max(0, next.length - 1)); setQueueIndex(nextIndex); persist({ queue: next, queueIndex: nextIndex }); return next; }); }, [persist, queueIndex]);
  const stop = useCallback(() => { const audio = audioRef.current; if (audio) { audio.pause(); audio.removeAttribute('src'); audio.load(); } setCurrent(null); setPlaying(false); setPosition(0); setDuration(0); setQueueIndex(0); setQueue([]); persist({ queue: [], queueIndex: 0, position: 0 }); }, [persist]);

  useEffect(() => {
    if (!('mediaSession' in navigator)) return;
    const action = (name: MediaSessionAction, handler: () => void) => { try { navigator.mediaSession.setActionHandler(name, handler); } catch {} };
    action('play', () => { if (current) toggle(current); }); action('pause', () => { audioRef.current?.pause(); }); action('nexttrack', next); action('previoustrack', previous); action('seekbackward', () => seek(Math.max(0, position - 10))); action('seekforward', () => seek(Math.min(duration, position + 10)));
    return () => { for (const name of ['play', 'pause', 'nexttrack', 'previoustrack', 'seekbackward', 'seekforward'] as MediaSessionAction[]) { try { navigator.mediaSession.setActionHandler(name, null); } catch {} } };
  }, [current, duration, next, position, previous, seek, toggle]);

  useEffect(() => { if (!('mediaSession' in navigator) || !current) return; navigator.mediaSession.metadata = new MediaMetadata({ title: current.title, artist: current.artistName ?? 'Unknown artist', album: current.albumTitle }); }, [current]);
  useEffect(() => () => { audioRef.current?.pause(); window.clearTimeout(saveTimer.current); }, []);
  const value = useMemo<PlayerState>(() => ({ current: current ? { track: current } : null, playing, position, duration, queue, queueIndex, repeatMode, shuffle, toggle, playQueue, enqueue, playNext, next, previous, seek, setShuffle, cycleRepeat, stop, clearQueue, removeFromQueue }), [current, playing, position, duration, queue, queueIndex, repeatMode, shuffle, toggle, playQueue, enqueue, playNext, next, previous, seek, setShuffle, cycleRepeat, stop, clearQueue, removeFromQueue]);
  return <PlayerContext.Provider value={value}>{children}<audio ref={audioRef} preload="none" onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onEnded={next} onTimeUpdate={(event) => { setPosition(event.currentTarget.currentTime); persist({ position: event.currentTarget.currentTime }); }} onLoadedMetadata={(event) => setDuration(event.currentTarget.duration || 0)} onError={() => setPlaying(false)} /></PlayerContext.Provider>;
}
export function usePlayer(): PlayerState { const context = useContext(PlayerContext); if (!context) throw new Error('usePlayer must be used inside <PlayerProvider>.'); return context; }
