import { useEffect, useState } from 'react';
import { fetchMusicMetadata, updateMusicMetadata, type MusicMetadata, type TrackSummary } from '../api/music';

export function MusicMetadataEditor({ track, onSaved }: { track: TrackSummary; onSaved: () => void }) {
  const [metadata, setMetadata] = useState<MusicMetadata | null>(null);
  const [open, setOpen] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!open) return; const controller = new AbortController(); setError(null); fetchMusicMetadata(track.id, controller.signal).then(setMetadata).catch((e: unknown) => { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'Could not read metadata.'); }); return () => controller.abort(); }, [open, track.id]);
  const update = (key: keyof MusicMetadata, value: string) => setMetadata((current) => current ? { ...current, [key]: value || null } : current);
  const save = async () => { if (!metadata || !confirmed) return; setBusy(true); setError(null); try { await updateMusicMetadata(track.id, { title: metadata.title, trackArtist: metadata.trackArtist, albumArtist: metadata.albumArtist, album: metadata.album, trackNumber: metadata.trackNumber, discNumber: metadata.discNumber, year: metadata.year, genre: metadata.genre, confirmed: true }); setOpen(false); setConfirmed(false); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not write metadata.'); } finally { setBusy(false); } };
  return <><button type="button" aria-label={`Edit metadata for ${track.title}`} onClick={() => setOpen(true)} className="icon-btn">✎</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" role="dialog" aria-modal="true" aria-labelledby={`metadata-title-${track.id}`}><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-border bg-surface p-6 shadow-pop"><div className="flex items-center justify-between"><h2 id={`metadata-title-${track.id}`} className="text-lg font-semibold">Edit metadata</h2><button type="button" aria-label="Close metadata editor" onClick={() => setOpen(false)} className="icon-btn">×</button></div><p className="mt-1 text-sm text-secondary">{track.title} · {track.artistName ?? 'Unknown artist'}</p>{metadata === null && !error && <p className="mt-6 text-sm text-muted">Loading metadata…</p>}{error && <p role="alert" className="mt-4 text-sm text-danger">{error}</p>}{metadata && <div className="mt-5 grid gap-3 sm:grid-cols-2">{(['title','trackArtist','albumArtist','album','genre'] as const).map((key) => <label key={key} className="grid gap-1 text-sm"><span className="text-secondary">{key === 'trackArtist' ? 'Track artist' : key === 'albumArtist' ? 'Album artist' : key[0].toUpperCase() + key.slice(1)}</span><input value={metadata[key] ?? ''} onChange={(e) => update(key, e.target.value)} className="rounded-lg border border-border bg-surface px-3 py-2" /></label>)}{(['trackNumber','discNumber','year'] as const).map((key) => <label key={key} className="grid gap-1 text-sm"><span className="text-secondary">{key}</span><input type="number" value={metadata[key] ?? ''} onChange={(e) => setMetadata((current) => current ? { ...current, [key]: e.target.value ? Number(e.target.value) : null } : current)} className="rounded-lg border border-border bg-surface px-3 py-2" /></label>)}</div>}{metadata && <label className="mt-5 flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /><span>I understand this writes tags to the local audio file.</span></label>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-lg border border-border px-4 py-2 text-sm">Cancel</button><button type="button" disabled={!metadata || !confirmed || busy} onClick={() => void save()} className="rounded-lg bg-accent px-4 py-2 text-sm text-white disabled:opacity-50">{busy ? 'Saving…' : 'Save to file'}</button></div></div></div>}</>;
}
