import { formatDuration, type TrackSummary } from '../api/music';
import { usePlayer } from '../hooks/usePlayer';
import { PlayIcon } from './icons';

export function MusicPlayerBar() {
  const { current, playing, position, duration, queue, repeatMode, shuffle, toggle, next, previous, seek, setShuffle, cycleRepeat, stop, clearQueue } = usePlayer();
  if (!current) return null;
  return <div className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-surface/95 backdrop-blur" data-testid="player-bar"><div className="mx-auto flex max-w-6xl items-center gap-2 px-4 py-3"><button type="button" aria-label="Previous track" onClick={previous} className="icon-btn">‹</button><button type="button" aria-label={playing ? 'Pause' : 'Play'} onClick={() => toggle(current.track)} className="icon-btn text-accent"><PlayIcon className="size-5" /></button><button type="button" aria-label="Next track" onClick={next} className="icon-btn">›</button><span className="hidden min-w-0 flex-1 sm:block"><span className="block truncate text-sm font-medium">{current.track.title}</span><span className="block truncate text-xs text-muted">{current.track.artistName ?? 'Unknown artist'} · {current.track.albumTitle}</span></span><button type="button" aria-label={`Shuffle ${shuffle ? 'on' : 'off'}`} aria-pressed={shuffle} onClick={() => setShuffle(!shuffle)} className={`icon-btn ${shuffle ? 'text-accent' : ''}`}>⇄</button><button type="button" aria-label={`Repeat ${repeatMode}`} onClick={cycleRepeat} className={`icon-btn ${repeatMode !== 'off' ? 'text-accent' : ''}`}>↻</button><span className="text-xs tabular-nums text-muted">{formatDuration(position)} / {formatDuration(duration)}</span><input aria-label="Seek" type="range" min={0} max={Math.max(1, Math.floor(duration))} value={Math.floor(position)} onChange={(event) => seek(Number(event.target.value))} className="hidden w-40 md:block" /><details className="relative"><summary className="icon-btn list-none cursor-pointer" aria-label={`Queue (${queue.length})`}>☷</summary><div className="absolute bottom-12 right-0 w-80 rounded-xl border border-border bg-surface p-3 shadow-pop"><div className="mb-2 flex items-center justify-between"><strong className="text-sm">Queue</strong><button type="button" className="text-xs text-muted hover:text-primary" onClick={clearQueue}>Clear</button></div><ol className="max-h-64 space-y-1 overflow-auto">{queue.map((item, index) => <li key={`${item.id}-${index}`} className={`flex items-center gap-2 rounded-lg px-2 py-1.5 text-xs ${index === queue.findIndex((x) => x.id === current.track.id) ? 'bg-accent-soft' : ''}`}><span className="w-5 text-muted">{index + 1}</span><span className="min-w-0 flex-1 truncate">{item.title}</span><span className="max-w-24 truncate text-muted">{item.artistName ?? 'Unknown'}</span></li>)}</ol></div></details><button type="button" aria-label="Stop" onClick={stop} className="icon-btn">×</button></div></div>;
}

export function QueueButton({ track }: { track: TrackSummary }) { const { enqueue, playNext } = usePlayer(); return <span className="flex shrink-0 gap-1"><button type="button" aria-label={`Play ${track.title} next`} onClick={() => playNext(track)} className="icon-btn">↟</button><button type="button" aria-label={`Add ${track.title} to queue`} onClick={() => enqueue(track)} className="icon-btn">＋</button></span>; }
