import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { useNavigate } from 'react-router-dom';
import { fetchLibraries, type Library } from '../api/libraries';
import { addMusicFavorite, albumCoverUrl, fetchMusicAlbums, fetchMusicArtists, fetchMusicFavorites, fetchMusicHistory, fetchMusicOverview, fetchMusicPlaylists, fetchMusicTopTracks, fetchMusicTracks, formatDuration, reindexMusic, removeMusicFavorite, type AlbumSummary, type ArtistSummary, type MusicFavorite, type MusicOverview, type MusicPlayHistory, type PlaylistSummary, type TrackSummary } from '../api/music';
import { MusicIcon } from '../components/icons';
import { MusicPlayerBar } from '../components/MusicPlayerBar';
import { MusicTrackMenu } from '../components/MusicTrackMenu';
import { ErrorState } from '../components/states/ErrorState';
import { LoadingState } from '../components/states/LoadingState';
import { EmptyState } from '../components/states/EmptyState';
import { usePlayer } from '../hooks/usePlayer';

type Layout = 'standard' | 'bento';

function Cover({ albumId, hasCover, className = '' }: { albumId?: string | null; hasCover?: boolean; className?: string }) {
  return albumId && hasCover ? <img src={albumCoverUrl(albumId)} alt="" loading="lazy" className={`object-cover ${className}`} /> : <div className={`grid place-items-center bg-surface-elevated text-primary/20 ${className}`}><MusicIcon className="size-8" /></div>;
}

function Header({ title, count, onSeeAll }: { title: string; count?: number; onSeeAll?: () => void }) {
  return <div className="mb-4 flex items-center justify-between gap-4"><div className="flex items-baseline gap-2"><h2 className="text-lg font-semibold tracking-tight text-primary">{title}</h2>{count !== undefined && <span className="text-xs text-tertiary">{count}</span>}</div>{onSeeAll && <button type="button" onClick={onSeeAll} className="rounded-lg px-2 py-1 text-xs font-medium text-secondary hover:bg-surface-elevated hover:text-primary">See all</button>}</div>;
}

function TrackCard({ track, favorite, onFavorite, onPlay, onChanged }: { track: TrackSummary; favorite: boolean; onFavorite: () => void; onPlay: () => void; onChanged: () => void }) {
  return <article className="group relative min-w-[210px] rounded-2xl border border-border bg-surface/70 p-3 transition hover:-translate-y-0.5 hover:bg-surface-elevated"><button type="button" onClick={onPlay} className="relative block w-full overflow-hidden rounded-xl text-left" aria-label={`Play ${track.title}`}><Cover albumId={track.albumId} hasCover={track.hasCover} className="aspect-square w-full rounded-xl" /><span className="absolute bottom-2 right-2 grid size-9 place-items-center rounded-full bg-primary text-background opacity-0 shadow-lg transition group-hover:opacity-100">▶</span></button><div className="mt-3 min-w-0 pr-14"><p className="truncate text-sm font-semibold text-primary">{track.title}</p><p className="truncate text-xs text-secondary">{track.artistName ?? 'Unknown artist'}</p><p className="mt-1 truncate text-[11px] text-tertiary">{track.albumTitle} · {formatDuration(track.durationSeconds)}</p></div><div className="absolute right-3 bottom-3 flex items-center gap-1"><button type="button" aria-label={favorite ? `Remove favorite ${track.title}` : `Favorite ${track.title}`} onClick={onFavorite} className={`grid size-8 place-items-center rounded-lg text-sm hover:bg-surface ${favorite ? 'text-accent' : 'text-tertiary hover:text-primary'}`}>{favorite ? '♥' : '♡'}</button><MusicTrackMenu track={track} onChanged={onChanged} /></div></article>;
}

function AlbumCard({ album, onOpen }: { album: AlbumSummary; onOpen: () => void }) { return <button type="button" onClick={onOpen} className="group min-w-[180px] text-left"><div className="overflow-hidden rounded-2xl border border-border bg-surface"><Cover albumId={album.id} hasCover={album.hasCover} className="aspect-square w-full transition duration-300 group-hover:scale-[1.02]" /></div><p className="mt-3 truncate text-sm font-semibold text-primary">{album.title}</p><p className="truncate text-xs text-secondary">{album.artistName ?? 'Unknown artist'}{album.year ? ` · ${album.year}` : ''}</p></button>; }
function ArtistCard({ artist, onOpen }: { artist: ArtistSummary; onOpen: () => void }) { return <button type="button" onClick={onOpen} className="group min-w-[145px] text-center"><div className="mx-auto grid aspect-square w-full place-items-center rounded-full border border-border bg-surface-elevated text-3xl font-semibold text-primary/60 transition group-hover:-translate-y-0.5 group-hover:border-accent/30 group-hover:text-primary"><span>{artist.name.trim().slice(0, 1).toUpperCase() || '?'}</span></div><p className="mt-3 truncate text-sm font-semibold text-primary">{artist.name}</p><p className="text-xs text-tertiary">Artist</p></button>; }
function PlaylistCard({ playlist, onOpen }: { playlist: PlaylistSummary; onOpen: () => void }) { return <button type="button" onClick={onOpen} className="group min-w-[220px] rounded-2xl border border-border bg-surface/70 p-4 text-left hover:bg-surface-elevated"><div className="grid aspect-[1.45] place-items-center rounded-xl bg-surface-elevated text-primary/20"><MusicIcon className="size-9" /></div><p className="mt-3 truncate text-sm font-semibold text-primary">{playlist.name}</p><p className="mt-1 text-xs text-tertiary">{playlist.isSmart ? 'Smart playlist' : 'Playlist'}</p></button>; }
function Carousel({ children }: { children: ReactNode }) { return <div className="flex snap-x gap-4 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{children}</div>; }

export function MusicDashboardPhase2Page() {
  const navigate = useNavigate();
  const player = usePlayer();
  const [libraries, setLibraries] = useState<Library[] | null>(null);
  const [libraryId, setLibraryId] = useState('');
  const [tracks, setTracks] = useState<TrackSummary[]>([]);
  const [albums, setAlbums] = useState<AlbumSummary[]>([]);
  const [artists, setArtists] = useState<ArtistSummary[]>([]);
  const [playlists, setPlaylists] = useState<PlaylistSummary[]>([]);
  const [history, setHistory] = useState<MusicPlayHistory[]>([]);
  const [top, setTop] = useState<Array<{ trackId: string; plays: number; playedSeconds: number }>>([]);
  const [favorites, setFavorites] = useState<MusicFavorite[]>([]);
  const [overview, setOverview] = useState<MusicOverview | null>(null);
  const [layout, setLayout] = useState<Layout>(() => localStorage.getItem('onidash.music.dashboard.layout') === 'bento' ? 'bento' : 'standard');
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const load = async (id: string) => {
    try {
      const [t, al, ar, p, h, tt, f, o] = await Promise.all([fetchMusicTracks(id, { limit: 1000 }), fetchMusicAlbums(id, { limit: 500 }), fetchMusicArtists(id, { limit: 500 }), fetchMusicPlaylists(), fetchMusicHistory({ limit: 50 }), fetchMusicTopTracks(20), fetchMusicFavorites(), fetchMusicOverview()]);
      setTracks(t); setAlbums(al); setArtists(ar); setPlaylists(p); setHistory(h); setTop(tt); setFavorites(f); setOverview(o); setError(null);
    } catch (e) { setError(e instanceof Error ? e.message : 'Could not load the music dashboard.'); }
  };
  useEffect(() => { const controller = new AbortController(); fetchLibraries(controller.signal).then(all => { setLibraries(all); if (all[0]) setLibraryId(v => v || all[0].id); }).catch(e => { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'Could not load libraries.'); }); return () => controller.abort(); }, []);
  useEffect(() => { if (libraryId) void load(libraryId); }, [libraryId]);
  useEffect(() => { localStorage.setItem('onidash.music.dashboard.layout', layout); }, [layout]);

  const favoriteIds = useMemo(() => new Set(favorites.filter(f => f.entityType === 'track').map(f => f.entityId)), [favorites]);
  const historyTracks = useMemo(() => history.map(h => tracks.find(t => t.id === h.trackId)).filter(Boolean) as TrackSummary[], [history, tracks]);
  const topTracks = useMemo(() => top.map(x => tracks.find(t => t.id === x.trackId)).filter(Boolean) as TrackSummary[], [top, tracks]);
  const recentlyAdded = useMemo(() => tracks.slice().sort((a, b) => (b.year ?? 0) - (a.year ?? 0)).slice(0, 12), [tracks]);
  const continueTrack = player.current ?? historyTracks[0] ?? recentlyAdded[0] ?? null;
  const continueHistory = continueTrack ? history.find(h => h.trackId === continueTrack.id) : undefined;
  const progress = continueTrack && player.current?.id === continueTrack.id ? player.position : (continueHistory?.playedSeconds ?? 0);

  const toggleFavorite = async (track: TrackSummary) => { try { if (favoriteIds.has(track.id)) await removeMusicFavorite('track', track.id); else await addMusicFavorite('track', track.id); await load(libraryId); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update favorite.'); } };
  const rescan = async () => { setBusy(true); try { await reindexMusic(libraryId); await load(libraryId); } catch (e) { setError(e instanceof Error ? e.message : 'Could not refresh the library.'); } finally { setBusy(false); } };
  const openWorkspace = () => navigate('/music/studio');
  const play = (track: TrackSummary) => player.toggle(track);

  if (error) return <ErrorState title="Music dashboard unavailable" message={error} onRetry={() => libraryId && void load(libraryId)} />;
  if (!libraries) return <LoadingState label="Loading Music…" />;
  if (!libraryId) return <EmptyState icon={<MusicIcon className="size-6" />} title="No music library" description="Create a music library and scan your audio folder to get started." />;

  const trackProps = (track: TrackSummary) => ({ track, favorite: favoriteIds.has(track.id), onFavorite: () => void toggleFavorite(track), onPlay: () => play(track), onChanged: () => void load(libraryId) });
  return <div className="pb-24">
    <header className="mb-7 flex flex-col gap-4 border-b border-border pb-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-accent">Music</p><h1 className="mt-1 text-3xl font-bold tracking-[-.035em] text-primary sm:text-4xl">Your library</h1><p className="mt-2 text-sm text-secondary">Play, manage, and organize your local music collection.</p></div><div className="flex flex-wrap items-center gap-2"><select aria-label="Music library" value={libraryId} onChange={e => setLibraryId(e.target.value)} className="rounded-xl border border-border bg-surface px-3 py-2 text-sm text-primary">{libraries.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select><button type="button" disabled={busy} onClick={() => void rescan()} className="rounded-xl border border-border bg-surface px-3 py-2 text-sm text-secondary hover:bg-surface-elevated hover:text-primary">{busy ? 'Refreshing…' : 'Refresh'}</button><div className="flex rounded-xl border border-border bg-surface p-1"><button type="button" aria-label="Standard" onClick={() => setLayout('standard')} className={`rounded-lg px-3 py-1.5 text-xs ${layout === 'standard' ? 'bg-primary text-background' : 'text-secondary'}`}>Standard</button><button type="button" aria-label="Bento" onClick={() => setLayout('bento')} className={`rounded-lg px-3 py-1.5 text-xs ${layout === 'bento' ? 'bg-primary text-background' : 'text-secondary'}`}>Bento</button></div></div></header>
    {layout === 'standard' ? <div className="space-y-10"><ContinueHero track={continueTrack} progress={progress} favorite={continueTrack ? favoriteIds.has(continueTrack.id) : false} onPlay={() => continueTrack && play(continueTrack)} onFavorite={() => continueTrack && void toggleFavorite(continueTrack)} /><Stats overview={overview} />{historyTracks.length > 0 && <section><Header title="Recently played" count={historyTracks.length} onSeeAll={openWorkspace} /><Carousel>{historyTracks.slice(0, 12).map(t => <TrackCard key={t.id} {...trackProps(t)} />)}</Carousel></section>}{topTracks.length > 0 && <section><Header title="Most played" count={topTracks.length} onSeeAll={openWorkspace} /><Carousel>{topTracks.slice(0, 12).map(t => <TrackCard key={t.id} {...trackProps(t)} />)}</Carousel></section>}{recentlyAdded.length > 0 && <section><Header title="Recently added" count={recentlyAdded.length} onSeeAll={openWorkspace} /><Carousel>{recentlyAdded.map(t => <TrackCard key={t.id} {...trackProps(t)} />)}</Carousel></section>}<section><Header title="Albums" count={overview?.albums ?? albums.length} onSeeAll={openWorkspace} /><Carousel>{albums.slice(0, 16).map(a => <AlbumCard key={a.id} album={a} onOpen={openWorkspace} />)}</Carousel></section><section><Header title="Artists" count={overview?.artists ?? artists.length} onSeeAll={openWorkspace} /><Carousel>{artists.slice(0, 16).map(a => <ArtistCard key={a.id} artist={a} onOpen={openWorkspace} />)}</Carousel></section>{playlists.length > 0 && <section><Header title="Playlists" count={overview?.playlists ?? playlists.length} onSeeAll={openWorkspace} /><Carousel>{playlists.slice(0, 12).map(p => <PlaylistCard key={p.id} playlist={p} onOpen={openWorkspace} />)}</Carousel></section>}</div> : <Bento track={continueTrack} progress={progress} history={historyTracks} top={topTracks} albums={albums} artists={artists} playlists={playlists} trackProps={trackProps} player={player} onPlay={play} onSeeAll={openWorkspace} />}
    <MusicPlayerBar />
  </div>;
}

function ContinueHero({ track, progress, favorite, onPlay, onFavorite }: { track: TrackSummary | null; progress: number; favorite: boolean; onPlay: () => void; onFavorite: () => void }) { if (!track) return <section className="rounded-3xl border border-border bg-surface p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">Continue listening</p><h2 className="mt-2 text-2xl font-semibold text-primary">Nothing queued yet</h2><p className="mt-2 text-sm text-secondary">Start playing music and oniDash will remember your place.</p></section>; const duration = track.durationSeconds ?? 0; const safe = Math.min(Math.max(progress, 0), duration); const percent = duration ? safe / duration * 100 : 0; const technical = [track.genre, track.year ? String(track.year) : null, track.trackNumber ? `Track ${track.trackNumber}` : null, track.discNumber ? `Disc ${track.discNumber}` : null].filter(Boolean).join(' · '); return <section className="relative overflow-hidden rounded-3xl border border-border bg-surface"><div className="absolute inset-0 opacity-[.06]" style={track.albumId ? { backgroundImage: `url(${albumCoverUrl(track.albumId)})`, backgroundPosition: 'center', backgroundSize: 'cover', filter: 'blur(30px)' } : undefined} /><div className="relative grid items-center gap-7 p-5 sm:p-8 lg:grid-cols-[280px_1fr] lg:p-10"><div className="overflow-hidden rounded-2xl border border-border bg-surface-elevated shadow-2xl"><Cover albumId={track.albumId} hasCover={track.hasCover} className="aspect-square w-full" /></div><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.2em] text-accent">Continue listening</p><h2 className="mt-3 truncate text-3xl font-bold tracking-[-.04em] text-primary sm:text-5xl">{track.title}</h2><p className="mt-2 truncate text-base text-secondary">{track.artistName ?? 'Unknown artist'} <span className="text-tertiary">·</span> {track.albumTitle}</p>{technical && <p className="mt-4 text-xs text-tertiary">{technical}</p>}<div className="mt-7"><div className="h-1.5 overflow-hidden rounded-full bg-primary/10"><div className="h-full rounded-full bg-accent transition-all" style={{ width: `${percent}%` }} /></div><div className="mt-2 flex justify-between text-[11px] tabular-nums text-tertiary"><span>{formatDuration(safe)}</span><span>{formatDuration(duration)}</span></div></div><div className="mt-5 flex gap-2"><button type="button" onClick={onPlay} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-background">▶ {percent > 0 ? 'Continue' : 'Play'}</button><button type="button" onClick={onFavorite} className="rounded-xl border border-border bg-surface-elevated px-4 py-2.5 text-sm text-primary">{favorite ? '♥ Favorited' : '♡ Favorite'}</button></div></div></div></section>; }
function Stats({ overview }: { overview: MusicOverview | null }) { return <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Tracks', overview?.tracks ?? 0], ['Albums', overview?.albums ?? 0], ['Artists', overview?.artists ?? 0], ['Listening', overview ? `${Math.floor(overview.listeningSeconds / 3600)}h` : '0h']].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-border bg-surface/60 px-4 py-4"><p className="text-xs text-tertiary">{label}</p><p className="mt-1 text-xl font-semibold text-primary">{value}</p></div>)}</div>; }
function Bento({ track, progress, history, top, albums, artists, playlists, trackProps, player, onPlay, onSeeAll }: { track: TrackSummary | null; progress: number; history: TrackSummary[]; top: TrackSummary[]; albums: AlbumSummary[]; artists: ArtistSummary[]; playlists: PlaylistSummary[]; trackProps: (t: TrackSummary) => { track: TrackSummary; favorite: boolean; onFavorite: () => void; onPlay: () => void; onChanged: () => void }; player: ReturnType<typeof usePlayer>; onPlay: (t: TrackSummary) => void; onSeeAll: () => void }) { return <div className="grid auto-rows-[minmax(150px,auto)] grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-4"><div className="md:col-span-2 xl:col-span-3"><ContinueHero track={track} progress={progress} favorite={track ? trackProps(track).favorite : false} onPlay={() => track && onPlay(track)} onFavorite={() => track && void trackProps(track).onFavorite()} /></div><Panel title="Library" className="xl:col-span-1" onSeeAll={onSeeAll}><div className="grid grid-cols-2 gap-2"><MiniStat label="Tracks" value={history.length + top.length ? 'Ready' : 0} /><MiniStat label="Albums" value={albums.length} /><MiniStat label="Artists" value={artists.length} /><MiniStat label="Playlists" value={playlists.length} /></div></Panel><Panel title="Recently played" className="md:col-span-2" onSeeAll={onSeeAll}><MiniList tracks={history.slice(0, 5)} player={player} onPlay={onPlay} /></Panel><Panel title="Most played" className="md:col-span-2" onSeeAll={onSeeAll}><MiniList tracks={top.slice(0, 5)} player={player} onPlay={onPlay} /></Panel><Panel title="Albums" className="md:col-span-2" onSeeAll={onSeeAll}><Carousel>{albums.slice(0, 6).map(a => <AlbumCard key={a.id} album={a} onOpen={onSeeAll} />)}</Carousel></Panel><Panel title="Artists" className="md:col-span-2" onSeeAll={onSeeAll}><Carousel>{artists.slice(0, 6).map(a => <ArtistCard key={a.id} artist={a} onOpen={onSeeAll} />)}</Carousel></Panel>{playlists.length > 0 && <Panel title="Playlists" className="md:col-span-2 xl:col-span-4" onSeeAll={onSeeAll}><Carousel>{playlists.slice(0, 8).map(p => <PlaylistCard key={p.id} playlist={p} onOpen={onSeeAll} />)}</Carousel></Panel>}</div>; }
function Panel({ title, className = '', children, onSeeAll }: { title: string; className?: string; children: ReactNode; onSeeAll?: () => void }) { return <section className={`min-w-0 overflow-hidden rounded-3xl border border-border bg-surface/70 p-5 ${className}`}><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold text-primary">{title}</h2>{onSeeAll && <button type="button" onClick={onSeeAll} className="text-xs text-secondary hover:text-primary">See all</button>}</div>{children}</section>; }
function MiniStat({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl bg-surface-elevated p-3"><p className="text-[11px] text-tertiary">{label}</p><p className="mt-1 text-sm font-semibold text-primary">{value}</p></div>; }
function MiniList({ tracks, player, onPlay }: { tracks: TrackSummary[]; player: ReturnType<typeof usePlayer>; onPlay: (t: TrackSummary) => void }) { return <div className="space-y-1">{tracks.map((t, i) => <button type="button" key={t.id} onClick={() => onPlay(t)} className="flex w-full items-center gap-3 rounded-xl px-2 py-2 text-left hover:bg-surface-elevated"><span className="w-5 text-center text-xs text-tertiary">{String(i + 1).padStart(2, '0')}</span><Cover albumId={t.albumId} hasCover={t.hasCover} className="size-10 shrink-0 rounded-lg" /><span className="min-w-0 flex-1"><span className={`block truncate text-sm font-medium ${player.current?.id === t.id ? 'text-accent' : 'text-primary'}`}>{t.title}</span><span className="block truncate text-xs text-secondary">{t.artistName ?? 'Unknown artist'}</span></span><span className="text-xs text-tertiary">{formatDuration(t.durationSeconds)}</span></button>)}</div>; }
