import { useEffect, useMemo, useState } from 'react';
import { fetchContinueMedia, fetchRecentlyAdded, fetchRecentlyPlayed, fetchFavorites, type DashboardMediaItem } from '../api/dashboard';
import { LoadingState } from '../components/states/LoadingState';
import { EmptyState } from '../components/states/EmptyState';

type Filter = 'all' | 'music' | 'movie' | 'anime' | 'manga' | 'book';
export function MediaCommandCenterPage() {
  const [items, setItems] = useState<DashboardMediaItem[]>([]);
  const [filter, setFilter] = useState<Filter>('all');
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  useEffect(() => { const c = new AbortController(); Promise.all([fetchContinueMedia(20,c.signal), fetchRecentlyAdded(20,c.signal), fetchRecentlyPlayed(20,c.signal), fetchFavorites(20,c.signal)]).then(xs => { const map = new Map<string, DashboardMediaItem>(); xs.flat().forEach(x => map.set(x.id, x)); setItems([...map.values()]); }).catch(() => {}).finally(() => { if (!c.signal.aborted) setLoading(false); }); return () => c.abort(); }, []);
  const visible = useMemo(() => { const q=query.trim().toLowerCase(); return items.filter(x => (filter==='all' || x.mediaType.toLowerCase()===filter) && (!q || x.title.toLowerCase().includes(q))); }, [items, filter, query]);
  if (loading) return <LoadingState label="Loading command center…" />;
  return <div className="space-y-7 pb-10"><header className="rounded-3xl border border-border bg-surface-elevated p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.22em] text-accent">Media command center</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Everything, one surface.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-secondary">A focused control room for the local collection — search across media, jump into libraries, and keep the next thing to watch, read, or play close at hand.</p><div className="mt-5 flex flex-col gap-2 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your entire collection…" className="flex-1 rounded-xl border border-border bg-surface px-4 py-3 text-sm" /><div className="flex flex-wrap gap-1 rounded-xl border border-border bg-surface p-1">{(['all','music','movie','anime','manga','book'] as Filter[]).map(x=><button key={x} type="button" onClick={()=>setFilter(x)} className={`rounded-lg px-3 py-2 text-xs font-semibold capitalize ${filter===x?'bg-surface-elevated text-primary shadow-card':'text-muted hover:text-primary'}`}>{x}</button>)}</div></div></header>{visible.length===0?<EmptyState title="No matching media" description="Try another title or media type." />:<section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">Library results</h2><span className="text-xs text-tertiary">{visible.length} items</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map(item=><article key={item.id} className="rounded-2xl border border-border bg-surface p-4 shadow-card transition hover:border-accent/40"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-accent-soft px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-accent">{item.mediaType}</span>{item.isFavorite&&<span className="text-accent">♥</span>}</div><h3 className="mt-4 truncate font-semibold">{item.title}</h3><p className="mt-1 text-xs text-secondary">{new Date(item.timestamp).toLocaleDateString()}</p><button type="button" className="mt-4 rounded-lg border border-border px-3 py-2 text-xs font-medium hover:bg-surface-elevated">Open library</button></article>)}</div></section>}</div>;
}
