import { useEffect, useState } from 'react';
import { fetchMusicGenres, fetchMusicHealth, fetchMusicOverview, type MusicOverview } from '../api/music';
import { ErrorState } from '../components/states/ErrorState';
import { LoadingState } from '../components/states/LoadingState';
export function MusicInsightsPage() {
  const [data, setData] = useState<MusicOverview | null>(null); const [genres, setGenres] = useState<Array<{ genre: string; tracks: number }>>([]); const [health, setHealth] = useState<{ database: boolean; tracks: number } | null>(null); const [error, setError] = useState<string | null>(null);
  const load = () => Promise.all([fetchMusicOverview(), fetchMusicGenres(), fetchMusicHealth()]).then(([overview, genreRows, status]) => { setData(overview); setGenres(genreRows); setHealth(status); }).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Could not load Music insights.'));
  useEffect(() => { void load(); }, []);
  if (error) return <ErrorState title="Music insights unavailable" message={error} onRetry={() => { setError(null); void load(); }} />;
  if (!data) return <LoadingState label="Loading Music insights…" />;
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold">Music insights</h2><p className="mt-1 text-sm text-secondary">Local collection health and listening totals.</p></div><div className="grid grid-cols-2 gap-4 md:grid-cols-5">{[['Tracks', data.tracks], ['Albums', data.albums], ['Artists', data.artists], ['Playlists', data.playlists], ['Favorites', data.favorites]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-border bg-surface p-4"><p className="text-xs text-muted">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div><section className="rounded-2xl border border-border bg-surface p-5"><h3 className="font-semibold">Library health</h3><p className="mt-2 text-sm text-secondary">Database: {health?.database ? 'connected' : 'unavailable'} · Indexed tracks: {health?.tracks ?? 0}</p><p className="mt-1 text-sm text-secondary">Listening time: {Math.round(data.listeningSeconds / 60)} minutes</p></section><section className="rounded-2xl border border-border bg-surface p-5"><h3 className="font-semibold">Genres</h3>{genres.length === 0 ? <p className="mt-2 text-sm text-muted">No genres indexed yet.</p> : <ul className="mt-2 divide-y divide-border">{genres.map((row) => <li key={row.genre} className="flex justify-between py-2 text-sm"><span>{row.genre}</span><span className="text-muted">{row.tracks}</span></li>)}</ul>}</section></div>;
}
