import { useEffect, useState } from 'react';
import { createMusicPlaylist, deleteMusicPlaylist, fetchMusicPlaylist, fetchMusicPlaylists, formatDuration, type PlaylistSummary } from '../api/music';
import { ErrorState } from '../components/states/ErrorState';
import { EmptyState } from '../components/states/EmptyState';
import { LoadingState } from '../components/states/LoadingState';
import { MusicIcon } from '../components/icons';

export function PlaylistsPage() {
  const [playlists, setPlaylists] = useState<PlaylistSummary[] | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [detail, setDetail] = useState<Awaited<ReturnType<typeof fetchMusicPlaylist>> | null>(null);
  const [name, setName] = useState(''); const [smart, setSmart] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = () => fetchMusicPlaylists().then(setPlaylists).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Could not load playlists.'));
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (selected) fetchMusicPlaylist(selected).then(setDetail).catch((e: unknown) => setError(e instanceof Error ? e.message : 'Could not load playlist.')); else setDetail(null); }, [selected]);
  const create = async () => { if (!name.trim()) return; try { const playlist = await createMusicPlaylist({ name, isSmart: smart, smartQuery: smart ? JSON.stringify({ sort: 'title', limit: 200 }) : undefined }); setName(''); setSmart(false); await load(); setSelected(playlist.id); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create playlist.'); } };
  const remove = async () => { if (!selected) return; await deleteMusicPlaylist(selected); setSelected(null); await load(); };
  if (error) return <ErrorState title="Playlists unavailable" message={error} onRetry={() => { setError(null); void load(); }} />;
  if (playlists === null) return <LoadingState label="Loading playlists…" />;
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold tracking-tight">Playlists</h2><p className="mt-1 text-sm text-secondary">Manual and smart playlists for your local Music library.</p></div><div className="flex flex-wrap gap-2"><input aria-label="Playlist name" value={name} onChange={(e) => setName(e.target.value)} placeholder="New playlist" className="rounded-lg border border-border bg-surface px-3 py-2" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={smart} onChange={(e) => setSmart(e.target.checked)} /> Smart</label><button type="button" onClick={() => void create()} className="rounded-lg bg-accent px-4 py-2 text-white">Create</button></div>{playlists.length === 0 ? <EmptyState icon={<MusicIcon className="size-6" />} title="No playlists yet" description="Create a manual or smart playlist to organize your tracks." /> : <div className="grid gap-6 md:grid-cols-[18rem_1fr]"><ul className="space-y-2">{playlists.map((playlist) => <li key={playlist.id}><button type="button" onClick={() => setSelected(playlist.id)} className={`w-full rounded-lg border px-3 py-2 text-left ${selected === playlist.id ? 'border-accent bg-accent-soft' : 'border-border bg-surface'}`}>{playlist.name}<span className="ml-2 text-xs text-muted">{playlist.isSmart ? 'Smart' : 'Manual'}</span></button></li>)}</ul>{detail && <section><div className="mb-3 flex items-center justify-between"><h3 className="text-lg font-semibold">{detail.name}</h3><button type="button" onClick={() => void remove()} className="rounded-lg border border-danger px-3 py-1.5 text-sm text-danger">Delete</button></div>{detail.tracks.length === 0 ? <p className="text-sm text-muted">No tracks match this playlist yet.</p> : <ul className="divide-y divide-border rounded-xl border border-border bg-surface">{detail.tracks.map((track) => <li key={track.id} className="flex items-center justify-between px-4 py-3"><span><span className="block text-sm font-medium">{track.title}</span><span className="text-xs text-muted">{track.artistName ?? 'Unknown artist'} · {track.albumTitle}</span></span><span className="text-xs text-muted">{formatDuration(track.durationSeconds)}</span></li>)}</ul>}</section>}</div>}</div>;
}
