import { apiFetch } from './client';
export interface ArtistSummary { id: string; name: string; }
export interface AlbumSummary { id: string; title: string; artistName: string | null; year: number | null; hasCover: boolean; }
export interface TrackSummary { id: string; mediaItemId: string; title: string; artistName: string | null; albumTitle: string; albumId: string | null; hasCover: boolean; trackNumber: number | null; discNumber: number | null; year: number | null; durationSeconds: number | null; genre: string | null; rating: number; }
export interface MusicMetadata { title: string | null; trackArtist: string | null; albumArtist: string | null; album: string | null; trackNumber: number | null; discNumber: number | null; year: number | null; durationSeconds: number | null; genre: string | null; }
export interface MusicFavorite { id: string; entityType: string; entityId: string; createdAtUtc: string; }
export interface MusicPlayHistory { id: string; trackId: string; startedAtUtc: string; completedAtUtc: string | null; playedSeconds: number; completionRatio: number; source: string; }
export interface PlaylistSummary { id: string; name: string; description: string | null; isSmart: boolean; updatedAtUtc: string; }
export interface PlaylistTrack extends TrackSummary { itemId: string | null; }
export interface PlaylistDetail extends PlaylistSummary { smartQuery: string | null; tracks: PlaylistTrack[]; }
export interface SmartRule { genre?: string; artistContains?: string; minYear?: number; maxYear?: number; sort?: 'title' | 'duration' | 'year'; limit?: number; }
export interface MusicOverview { tracks: number; albums: number; artists: number; playlists: number; favorites: number; listeningSeconds: number; }
export interface MusicHealth { database: boolean; tracks: number; lastUpdatedUtc: string | null; }
export interface MusicHomeTrack extends TrackSummary {}
export interface MusicContinueItem { trackId: string; positionSeconds: number; durationSeconds: number; updatedAtUtc: string; }
export interface MusicHomeCollections { continueListening: MusicContinueItem[]; recentlyPlayed: MusicHomeTrack[]; recentlyAdded: MusicHomeTrack[]; mostPlayed: MusicHomeTrack[]; favorites: MusicHomeTrack[]; topRated: MusicHomeTrack[]; neverPlayed: MusicHomeTrack[]; }
type PageOptions = { limit?: number; offset?: number; signal?: AbortSignal };
type MusicPage<T> = { items: T[]; offset: number; limit: number; total: number };
function pageParams(libraryId: string, options: PageOptions): URLSearchParams { const params = new URLSearchParams({ libraryId }); if (options.limit !== undefined) params.set('limit', String(options.limit)); if (options.offset !== undefined) params.set('offset', String(options.offset)); return params; }
async function fetchPage<T>(path: string, signal?: AbortSignal): Promise<T[]> { const page = await apiFetch<MusicPage<T>>(path, { signal }); return page.items; }
export function fetchMusicArtists(libraryId: string, options: PageOptions = {}): Promise<ArtistSummary[]> { return fetchPage<ArtistSummary>(`/music/artists?${pageParams(libraryId, options)}`, options.signal); }
export function fetchMusicAlbums(libraryId: string, options: PageOptions & { artistId?: string } = {}): Promise<AlbumSummary[]> { const p = pageParams(libraryId, options); if (options.artistId) p.set('artistId', options.artistId); return fetchPage<AlbumSummary>(`/music/albums?${p}`, options.signal); }
export function fetchMusicTracks(libraryId: string, options: PageOptions & { albumId?: string; artistId?: string } = {}): Promise<TrackSummary[]> { const p = pageParams(libraryId, options); if (options.albumId) p.set('albumId', options.albumId); if (options.artistId) p.set('artistId', options.artistId); return fetchPage<TrackSummary>(`/music/tracks?${p}`, options.signal); }
export function fetchMusicFavorites(signal?: AbortSignal): Promise<MusicFavorite[]> { return apiFetch<MusicFavorite[]>('/music/favorites', { signal }); }
export function addMusicFavorite(entityType: 'track' | 'album' | 'artist', entityId: string): Promise<void> { return apiFetch<void>('/music/favorites', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ entityType, entityId }) }); }
export function removeMusicFavorite(entityType: string, entityId: string): Promise<void> { return apiFetch<void>(`/music/favorites/${encodeURIComponent(entityType)}/${encodeURIComponent(entityId)}`, { method: 'DELETE' }); }
export function fetchMusicHistory(options: PageOptions = {}): Promise<MusicPlayHistory[]> { const p = new URLSearchParams(); if (options.limit !== undefined) p.set('limit', String(options.limit)); if (options.offset !== undefined) p.set('offset', String(options.offset)); return apiFetch<MusicPlayHistory[]>(`/music/history?${p}`, { signal: options.signal }); }
export function recordMusicPlay(trackId: string, playedSeconds: number, completionRatio: number, source = 'local'): Promise<void> { return apiFetch<void>(`/music/tracks/${encodeURIComponent(trackId)}/play`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ playedSeconds, completionRatio, source }) }); }
export function fetchMusicPlaybackState(trackId: string, signal?: AbortSignal): Promise<{ positionSeconds: number; completed: boolean; updatedAtUtc: string } | null> { return apiFetch<{ positionSeconds: number; completed: boolean; updatedAtUtc: string } | null>(`/music/tracks/${encodeURIComponent(trackId)}/playback-state`, { signal }); }
export function saveMusicPlaybackState(trackId: string, positionSeconds: number, completed = false): Promise<void> { return apiFetch<void>(`/music/tracks/${encodeURIComponent(trackId)}/playback-state`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ positionSeconds, completed }) }); }
export function fetchMusicPlaylists(signal?: AbortSignal): Promise<PlaylistSummary[]> { return apiFetch<PlaylistSummary[]>('/music/playlists', { signal }); }
export function fetchMusicPlaylist(id: string, options: PageOptions = {}): Promise<PlaylistDetail> { const p = new URLSearchParams(); if (options.limit !== undefined) p.set('limit', String(options.limit)); if (options.offset !== undefined) p.set('offset', String(options.offset)); return apiFetch<PlaylistDetail>(`/music/playlists/${encodeURIComponent(id)}?${p}`, { signal: options.signal }); }
export function createMusicPlaylist(payload: { name: string; description?: string; isSmart?: boolean; smartQuery?: string }): Promise<PlaylistSummary> { return apiFetch<PlaylistSummary>('/music/playlists', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); }
export function updateMusicPlaylist(id: string, payload: { name: string; description?: string; isSmart?: boolean; smartQuery?: string }): Promise<PlaylistSummary> { return apiFetch<PlaylistSummary>(`/music/playlists/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); }
export function deleteMusicPlaylist(id: string): Promise<void> { return apiFetch<void>(`/music/playlists/${encodeURIComponent(id)}`, { method: 'DELETE' }); }
export function addTrackToMusicPlaylist(playlistId: string, trackId: string, position?: number): Promise<void> { return apiFetch<void>(`/music/playlists/${encodeURIComponent(playlistId)}/items`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ trackId, position }) }); }
export function removeTrackFromMusicPlaylist(playlistId: string, itemId: string): Promise<void> { return apiFetch<void>(`/music/playlists/${encodeURIComponent(playlistId)}/items/${encodeURIComponent(itemId)}`, { method: 'DELETE' }); }
export function reorderMusicPlaylist(playlistId: string, itemIds: string[]): Promise<void> { return apiFetch<void>(`/music/playlists/${encodeURIComponent(playlistId)}/items/reorder`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ itemIds }) }); }
export function saveMusicQueueToPlaylist(playlistId: string, trackIds: string[]): Promise<{ added: number }> { return apiFetch<{ added: number }>(`/music/playlists/${encodeURIComponent(playlistId)}/save-queue`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ trackIds }) }); }
export function fetchMusicHomeCollections(libraryId: string, limit = 12, signal?: AbortSignal): Promise<MusicHomeCollections> { const p = new URLSearchParams({ libraryId, limit: String(limit) }); return apiFetch<MusicHomeCollections>(`/music/collections/home?${p}`, { signal }); }
export function fetchMusicMetadata(trackId: string, signal?: AbortSignal): Promise<MusicMetadata> { return apiFetch<MusicMetadata>(`/music/tracks/${encodeURIComponent(trackId)}/metadata`, { signal }); }
export function fetchMusicTrack(trackId: string, signal?: AbortSignal): Promise<TrackSummary> { return apiFetch<TrackSummary>(`/music/tracks/${encodeURIComponent(trackId)}`, { signal }); }
export function updateMusicMetadata(trackId: string, update: Partial<Omit<MusicMetadata, 'durationSeconds'>> & { confirmed: true }): Promise<void> { return apiFetch<void>(`/music/tracks/${encodeURIComponent(trackId)}/metadata`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(update) }); }
export function fetchMusicRating(trackId: string, signal?: AbortSignal): Promise<number> { return apiFetch<{ rating: number }>(`/music/tracks/${encodeURIComponent(trackId)}/rating`, { signal }).then((x) => x.rating); }
export function updateMusicRating(trackId: string, rating: number): Promise<void> { return apiFetch<void>(`/music/tracks/${encodeURIComponent(trackId)}/rating`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rating }) }); }
export function fetchMusicLyrics(trackId: string, signal?: AbortSignal): Promise<{ text: string; synchronized: boolean }> { return apiFetch<{ text: string; synchronized: boolean }>(`/music/tracks/${encodeURIComponent(trackId)}/lyrics`, { signal }); }
export function saveMusicLyrics(trackId: string, text: string, synchronized: boolean): Promise<void> { return apiFetch<void>(`/music/tracks/${encodeURIComponent(trackId)}/lyrics`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text, synchronized }) }); }
export function searchMusicLyrics(query: { track: string; artist?: string; album?: string }, signal?: AbortSignal) { const p = new URLSearchParams({ track: query.track }); if (query.artist) p.set('artist', query.artist); if (query.album) p.set('album', query.album); return apiFetch<Array<{ id: string; title: string; artist: string; album: string; synced: boolean; plainText: string; syncedText: string | null; source: string }>>(`/music/providers/lyrics/search?${p}`, { signal }); }
export function fetchMusicInfo(trackId: string, signal?: AbortSignal) { return apiFetch<{ id: string; title: string; artistName: string | null; album: string; rating: number; path: string; sizeBytes: number; modifiedUtc: string; extension: string }>(`/music/tracks/${encodeURIComponent(trackId)}/info`, { signal }); }
export function renameMusicTrack(trackId: string, fileName: string): Promise<void> { return apiFetch<void>(`/music/tracks/${encodeURIComponent(trackId)}/rename`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fileName }) }); }
export function deleteMusicTrack(trackId: string, deleteFile = false): Promise<void> { return apiFetch<void>(`/music/tracks/${encodeURIComponent(trackId)}?deleteFile=${deleteFile}`, { method: 'DELETE' }); }
export function fetchMusicOverview(signal?: AbortSignal): Promise<MusicOverview> { return apiFetch<MusicOverview>('/music/statistics/overview', { signal }); }
export function fetchMusicHealth(signal?: AbortSignal): Promise<MusicHealth> { return apiFetch<MusicHealth>('/music/health', { signal }); }
export function fetchMusicTopTracks(limit = 20, signal?: AbortSignal) { return apiFetch<Array<{ trackId: string; plays: number; playedSeconds: number }>>(`/music/statistics/top-tracks?limit=${limit}`, { signal }); }
export function fetchMusicGenres(signal?: AbortSignal) { return apiFetch<Array<{ genre: string; tracks: number }>>('/music/statistics/genres', { signal }); }
export function albumCoverUrl(albumId: string): string { return `/api/music/albums/${albumId}/cover`; }
export function trackStreamUrl(trackId: string): string { return `/api/music/tracks/${trackId}/stream`; }
export function reindexMusic(libraryId?: string): Promise<{ indexedTracks: number }> { return apiFetch<{ indexedTracks: number }>(libraryId ? `/music/reindex?libraryId=${encodeURIComponent(libraryId)}` : '/music/reindex', { method: 'POST' }); }
export function formatDuration(seconds: number | null): string { if (seconds === null || !Number.isFinite(seconds) || seconds < 0) return '–:––'; const total = Math.round(seconds); return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, '0')}`; }
